### ISSUE TITLE
Add a commit with -a command

### ISSUE THREAD

**Issue by treeder** [kemayo/sublime-text-git#174]
So it will automatically add/commit all tracked files.

**Comment by mbigras** [comment]
It looks like this is an old issue; however, I really do think that being able to Add All Files and then Quick 
Commit in one command would be a great feature. I've been trying to do this for about two days using `sublime.log_commands(True)` and trying to chain together `window.run_command("git_raw", {"command":"git add -A"})`  and `view.run_command("git_quick_commit")` in a plugin and then adding the plugin to the command palette

git_add_then_quick_commit.py
```python
import sublime, sublime_plugin

class GitAddThenQuickCommitCommand(sublime_plugin.WindowCommand):
    def run(self):
        self.window.run_command("git_raw", {"command":"git add -A"})
        self.view.run_command("git_quick_commit")
```
Default.sublime-commands
```
[
    // Define your custom Sublime commands here
    // Format is same as `key bindings` except replace `keys` with `caption`
    {
        // Name to show in Command Palette
        "caption": "Git: Add Then Quick Commit",
        // Command to invoke
        "command": "git_add_then_quick_commit",
        // Optional keyword arguments to provide to command
        //"args": {"key": "value"}
    }
]
```
The problem that I'm running into is: the command to "Git: Add All" is a "window" command and the command to "Git: Quick Commit" is a "view" command. I'm new to making plugins so I might be saying this wrong, but the main question I'm wondering is: How can I chain together those two commands? Thanks for your help! Also by the way, thanks for such a rad plugin, I've been using it a ton and it definitely helps :)

**Comment by kemayo** [comment]
So! The big problem you're going to run into here is that all of the Git plugin commands work fairly hard at being asynchronous. i.e. all git-operations go off into their own thread, so they won't have any chance of impacting the main UI thread. This means that trying to run several commands at the same time, as you're doing here, is going to run into issues.

Now, conveniently, what you're trying to do.... is actually already part of the Quick Commit command. `Git: Quick Commit (repo)` does `git add .` (which I should really change to `-A`, granted) followed by `git commit`.

**Comment by mbigras** [comment]
thanks for getting back to me on this @kemayo! I hear you about the asynchronous bit, it will be weird because there's no guarantee that the order I call them will be preserved when they hit the server correct? I haven't gotten too deep into it yet because I'm not sure how to get past the problem of combining the window and view commands as shown in my above post. Can you point me towards an example of a plugin that uses view+window commands? Or maybe you make two different plugins and link them together, I'm not sure. I don't have much experience with asynchronous programming or making python plugins but the concept seems to make sense, could we do something like `pause(400)` (I'm sure that's not the actually right thing to use but maybe you get where I'm going) right after we call git each git command to give them a chance to catch up? Because what I'm really trying to do is something like this:

1. Do some editing
2. Call a sync command
 1. Add all
 2. quick commit with a scripted commit message
 3. push
3. Everything is all up to date

And ya, totally man, please please change it to `-A` it's entire point of a quick commit, you can't quick commit if you can't add everything

Looking forward to hearing from you, and thanks for such an awesome plugin, it really has made my everyday workflow so much better. The only reason why I'm trying to implement sync functionality is because I'm working on building a repo full of markdown files because if I can edit all my markdown files in sublime, push them quickly up to github, view and edit my files in github, and eventually write a reasonable iOS app to edit/view markdown files in a github repo then I'll finally be able to say goodbye to evernote and I'm free to edit lists and notes like a real person again 😉

**Comment by kemayo** [comment]
So, given the async challenges, what I'd recommend doing is importing and extending one of the existing commands.

e.g. this thing which I'm typing into the comment box and haven't tested at all, but you'll get the idea

```
import Git  # assuming ST3; different in ST2
import sublime


class GitSyncCommand(Git.git.commit.GitQuickCommitCommand):
    def add_done(self, result, message):
        # This isn't the best inheritance, since we're not running super. This
        # is because we need to change the run_command call so there's a
        # callback.
        if result.strip():
            sublime.error_message("Error adding file:\n" + result)
            return
        self.run_command(['git', 'commit', '-m', message], self.commit_done)

    def commit_done(self, result):
        self.get_window().run_command('git_raw', {"command": "git pull"})
```

...approximately.

**Comment by mbigras** [comment]
Hmm I tried using this as a plugin and adding it to my Default.sublime-commands file. It did run...but it didn't work. I'm not sure what this plugin is doing so I've been bouncing around the unofficial documentation on writing plugins and going through your code. These are some guesses I have about what your above code is doing (and also some questions):

1. defining a new class `GitSyncCommand` (which by some sublime voodoo gets digested and becomes accessible for us as `git_sync` later) that extends the `GitQuickCommitCommand` which extends the `GitTextCommand`, which finally extends `TextCommand`. It seems like you're using `GitTextCommand` to do some house-keeping about checking if the files are actually in a git repo. Just as a side note, is this how you're able to toggle whether or not we see the `Git: xxxx` commands from the command palette?

2. You're adding a method named `add_done` which is not `run` as specified in the documentation but is this because sublime just knows that the first method in a plugin class is implicitly the `run` method?

3. your calling the `run_command` except you're giving it a callback, which doesn't seem like this is possible with Sublime's run command, except that's okay because you made your own `run_command` in `GitCommand` in `__init__.py` that has the ability to have a callback. So you give your custom method `commit_done` as the callback. So my big question at this stage is why are you choosing to `self.run_command  *commit*` first? Why aren't you doing something like `self.run_command *add all*` and then after running `self.run_command(['git', 'commit', '-m', message], self.commit_done)`? (note I put \*s there because I'm not sure what the correct syntax is)

4. You have your custom callback `commit_done` which as the name implies should run if the commit was done properly. However, inside here you choose to run `self.get_window().run_command('git_raw', {"command": "git pull"})`. I don't understand why you're choosing to pull here, because I'm pretty sure what we want to do after we commit is push so why isn't the callback something like `self.get_window().run_command('git_raw', {"command": "git push"})`? In any case, I tried changing it to `git push` and it still didn't work.

Summary: It looks to me like your code is doing something like this: `commit -> pull` when I'm thinking what we're really trying to do is something more like: `add all -> commit -> push`

So I tried making some modifications and messing around with it but I just got a blank dialog window pop up and the following error message:

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "git in /Users/max/Library/Application Support/Sublime Text 3/Installed Packages/Git.sublime-package", line 215, in run
NameError: global name '_has_warned' is not defined
```
Below is my code. It doesn't surprise me that it didn't work because I really don't know what I'm doing, but maybe it will help give you an idea of where I'm misunderstanding. Looking forward to hearing from you :) 

```
import Git  # assuming ST3; different in ST2
import sublime


class GitTrySyncCommand(Git.git.commit.GitQuickCommitCommand):
    def run(self, result):
        self.get_window().run_command("git_raw", {"command":"git add -A"})
        self.run_command("git_quick_commit", self.commit_done)

    def commit_done(self, result):
        self.get_window().run_command('git_raw', {"command": "git push"})
```
```
[
    // Define your custom Sublime commands here
    // Format is same as `key bindings` except replace `keys` with `caption`
    {
        // Name to show in Command Palette
        "caption": "Git: Add Then Quick Commit",
        // Command to invoke
        "command": "git_add_then_quick_commit",
    },
    {
        // Name to show in Command Palette
        "caption": "Git: Sync",
        // Command to invoke
        "command": "git_sync",
    },
    {
        // Name to show in Command Palette
        "caption": "Git: Try to Sync",
        // Command to invoke
        "command": "git_try_sync",
    }
]
```
