### ISSUE TITLE
git flow error in windows.

### ISSUE THREAD

**Issue by acthtml** [kemayo/sublime-text-git#339]
when i try 'git-flow feature start', it alert this:
![git-flow-error](https://cloud.githubusercontent.com/assets/1704913/2677634/a80805ea-c154-11e3-8014-63fabf03a05f.png)

**Comment by kujiy** [comment]
@acthtml you should add "\git-flow" at the end of the line.

#### default setting
```
	// point this the installation location of git-flow
	,"git_flow_command": "/usr/local/bin/git-flow"
```

#### so that you should write like this;

```
	// point this the installation location of git-flow
	,"git_flow_command": "C:\\Program Files\\Git\\usr\\bin\\git-flow"
```

### But I still got an error...
Windows 8.1/64bit, Sublimt Text 3 and latest this plugin.

![1210-01](https://cloud.githubusercontent.com/assets/6756543/11703183/326d9f4c-9f20-11e5-97a0-890c3ffff82e.png)
It says *OSError: [WinError 193] %1 is not a valid Win32 application."

I can use git-flow command from anywhere.
![1210-03](https://cloud.githubusercontent.com/assets/6756543/11703181/2ec239de-9f20-11e5-98d4-aae2e578ab8e.png)

I'm guessing that a reason is git-flow command is not a "Windows Application" like .exe and .bat.
Git-flow command is just a shell-script even though it doesn't have extention like .sh. 
So windows can't execute it directly.


Does anyone have an advice for me?
Does this plug-in not allow git-flow to windows?

**Comment by kujiy** [comment]
I fixed the problem in [the commit above](https://github.com/kujiy/SublimeText-Git/commit/3d475ddf689c0e505bec45f8d01f9571a4243a95) though I'm so bad at python.
I believe that my approach was terrible so that I hope someone could improve it or give me an advice.
Thanks.

**Comment by kujiy** [comment]
Okay I finally understood. I realized that I couldn't use the "git-flow" command in my cmd.exe.
(I can use the "git-flow" command only in my Git Bash.)

If we need to use "git-flow" with the hyphen in our cmd.exe, we have to use "sh.exe" with "git-flow" like this;
```
// This will work
$ sh  "C:\Program Files\Git\usr\bin\git-flow" version
```
Note; You have to set system path for sh.exe like here "C:\Program Files\Git\usr\bin".

Strangely, it won't work if you give cmd.exe sh.exe full path.
```
// This won't work
$  "C:\Program Files\Git\usr\bin\sh" "C:\Program Files\Git\usr\bin\git-flow" version
```

I could use "sh" in my commit but it needs to change your system env.
I don't want to importune you for it so that I choose the solution; changing "git-flow" to "git flow".

Alright, [this commit](33b56d8) is my last answer. I hope this helps someone.
