### ISSUE TITLE
using with SFTP remote

### ISSUE THREAD

**Issue by JacobIRR** [kemayo/sublime-text-git#451]
What if I am using the SFTP plugin to work on a file remotely? The files I am working on are already inside their own remote Git repo.... I assume that using 'git init' in the plugin will not work for this purpose, or it may create a problem in my remote repo... Is this a potentially new feature that I am referring to? or just something that I don't know how to do because it has not been covered?

**Comment by kemayo** [comment]
Can't say that I've tried using this over SFTP ever, so I'm making educated guesses here:

This plugin works by running the regular git CLI behind the scenes. (Switching to pygit or similar has been tempting.) Thus, if you could `cd` into whatever directory you're editing and run the relevant commands there, it should work. If you can't, it won't. Since SFTP doesn't transparently mount a directory somewhere, I suspect that this won't work. *Making* it work would require changes made by whatever SFTP setup your using, more than by this plugin.
