### ISSUE TITLE
Commands fail with error parsing plist xml.

### ISSUE THREAD

**Issue by josefbetancourt** [kemayo/sublime-text-git#457]
v1.0.3 on Sublime Text 2.0.2, On Windows 10. Git version 2.6.4.windows.1

Error loading syntax file "Package/./syntax/Git Commit
View.tmLanguage":Error parsing plist xml: Failed to open In file "Packages/./syntax/ Git Commit View.txLanguage"

**Comment by aldoreno** [comment]
@josefbetancourt Hi, I stumbled similar problem and found a way to resolve it.

So the problem is in `__init__.py` under `git` directory, specifically method `find_plugin_directory` method. The method's goal is "allowing for people who rename things", but since there are many OSes around and there are several Sublime Text versions, I think it's not that easy to defer. 

I also believe @kemayo seems to only focused on UNIX-derived OSes, so Windows users seems be a bit left behind and no one submit a PR for this yet.

Quickest way is to modify the returned value to: `return "Packages/Git` (if you install the package using Package Control, or replace "Git" with the name of directory where you extracted Sublime Text Git.

I hope it helps for anyone.

**Comment by kemayo** [comment]
I do use ST on Windows, mind you, and I don't see this problem occurring.

So many versions out there.

**Comment by aldoreno** [comment]
@kemayo maybe, just maybe, the problem only occurred specifically on Windows 10 (as reported above). I also occassionally use Windows 10 (while using Ubuntu fulltime, and no problem at all in Ubuntu).

Anyway, thank you for the plugin. <3 it so much!
