### ISSUE TITLE
Feature: quick commit whole repo

### ISSUE THREAD

**Issue by subhog** [kemayo/sublime-text-git#462]
Idea: create a convenience command that would:
- add all files (including untracked)
- commit.

The reasoning is that this would serve as a quick (one-keystroke) way of saving the current development state into git repository.

**Comment by kaarleenzz** [comment]
Would love to see this too.
It could work like a quick commit but add all files and ask for a message.

**Comment by cjaoude** [comment]
+ 1 with cherry on top.

**Comment by akalongman** [comment]
+10000

**Comment by akalongman** [comment]
I've created small plugin for that: https://gist.github.com/akalongman/43831b5b60413f66b8cd1c020c9e5124

And add in keybindings
```javascript
    {
        "keys": ["ctrl+alt+insert"],
        "command": "git_helper_commit"
    }
```

**Comment by kaarleenzz** [comment]
Downloaded gistfile1.txt, renamed it to GitHelper.py, put it under Packages/User, added the key binding under 'Key bindings - User', but nothing happens when I press ctrl + alt + insert.

@akalongman , do I also have to somehow install the package? Tried restarting sublime text, that didn't help either.

I'm using Sublime Text 3.

Thanks!

**Comment by akalongman** [comment]
Do you have installed Git package too?

**Comment by kaarleenzz** [comment]
Yes I do. Are there different Git packages? Maybe I have the wrong one.
