### ISSUE TITLE
"Toggle annotations" not working

### ISSUE THREAD

**Issue by darkred** [kemayo/sublime-text-git#482]
Using ST3 build 3118 x64 in win 10 x64, Git version 2.9.0, Git plugin 1.0.5.

To reproduce:

- (optionally) set ``"annotations": true` on plugin user settings, 
- modify a file of a git repository, 
- try `Command Palette | Git: Toggle Annotations` multiple times: nothing is displayed   

*(there are no relevant entries in console during this)*.

**Comment by slifin** [comment]
Can confirm this behaviour

**Comment by kemayo** [comment]
I did some Windows 10 investigation, and found some issues with temp files (which are important for live-diffing as is done for annotations). As such, I've committed  0f81c1737b0018eea1e12e0d0c32e8fab2238a47, which I think will help here. There was also another possible issue, if `diff` wasn't in your PATH which would have silently failed, which I've also cleaned up.

This has fixed what was happening for me. Could you confirm that it also fixes your issue?

**Comment by darkred** [comment]
I just tried it in ST3 build 3118 x64 in win 10 x64, Git version 2.9.2, Git plugin 1.0.6.
Unfortunately it doesn't work (there are no annotations).

Additionally, clicking `Command Palette | Git: Toggle Annotations` 
doesn't create the following entry in the package settings, neither does it toggle its value if it already exists 
(as it did in v1.0.5)
```
{
    "annotations": false
}
```

Also, about 

> There was also another possible issue, if `diff` wasn't in your PATH which would have silently failed, which I've also cleaned up.

What do you mean?
By default Git appends `;C:\Program Files\Git\cmd` in the system PATH.
Therefore `diff.exe` is not available in the PATH, as it is located in `C:\Program Files\Git\usr\bin`.
Should this be added to PATH too?
Either way, I just tried it, and it didn't help: still no annotations.

**Comment by kemayo** [comment]
Boring initial confirmation question: did you restart Sublime Text when updating the Git package? Because of the module structure, it won't necessarily reload the submodules -- like the annotations submodule -- without going to special lengths.

> Additionally, clicking Command Palette | Git: Toggle Annotations doesn't create the following entry in the package settings, neither does it toggle its value if it already exists (as it did in v1.0.5)

It actually didn't/doesn't change the package settings -- the Toggle Annotations command just sets a temporary setting on the current view, which tells it whether or not to run the annotations. The `annotations` setting just controls whether said temporary-setting is automatically-applied when you open a file.

> Should this be added to PATH too?

It's not necessary now, because that commit switched everything to go through `git diff`. Prior to that commit, it'd have been necessary.

**Comment by darkred** [comment]
> Boring initial confirmation question: did you restart Sublime Text when updating the Git package? Because of the module structure, it won't necessarily reload the submodules -- like the annotations submodule -- without going to special lengths.

Yes, of course. (I've edited my previous post, adding a console error I get).
<br>

> It actually didn't/doesn't change the package setting

You're right. Sorry, my mistake. I remembered it wrong.

<br>
I just tried v1.0.7 and now annotations work (and that error is fixed of course)! Thanks a lot!
