### ISSUE TITLE
add key bindings

### ISSUE THREAD

**Issue by ghostship** [kemayo/sublime-text-git#60]
There should be an ability to add key bindings for git features such as custom git command

**Comment by LeonardoGentile** [comment]
Thanks @spadgos, that worked!

Are you aware how to filter text passed to the command palette?

I mean by passing `"args": {"overlay": "command_palette", "text": "git "}` will show only the relevant command containing the "git" word. In my case it also includes other commands coming from other packages. For example `Git (SideBarGit)` and `BracketHighlither`, the last one because it contains the `g`,`i` and `t` letters.

My question: how can we filter out the other commands and show only the command of the exact match `git:`? Does the `text` param supports regex or similar? I was difficult to find anything on google about this argument

**Comment by spadgos** [comment]
It's exactly the same as opening the command palette and typing "g", "i", "t", so sublime text uses teh same fuzzy matching to display the matching commands. As far as I know there's no methods to get anything more powerful than that. If you changed it to be `"git: "` then that might help.

**Comment by LeonardoGentile** [comment]
@spadgos thanks, already tried with `git: ` and it has the same effect, ok I can live with it :+1:
